# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-16 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=150, verbose_name='school')),
                ('degree', models.CharField(max_length=150, verbose_name='degree')),
                ('topic', models.CharField(blank=True, max_length=150, verbose_name='topic')),
                ('result', models.CharField(blank=True, max_length=150, verbose_name='result')),
                ('description', models.TextField(blank=True, max_length=3000, verbose_name='description')),
                ('year', models.IntegerField(verbose_name='year')),
                ('month', models.IntegerField(verbose_name='month')),
            ],
        ),
        migrations.RenameModel(
            old_name='Skill',
            new_name='SkillType',
        ),
        migrations.RemoveField(
            model_name='training',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='entreprise',
        ),
        migrations.AddField(
            model_name='experience',
            name='enterprise',
            field=models.CharField(blank=True, max_length=200, verbose_name='enterprise'),
        ),
        migrations.DeleteModel(
            name='Training',
        ),
    ]
