# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-22 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_auto_20160922_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='address',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='phone',
        ),
        migrations.AddField(
            model_name='resume',
            name='date_birth',
            field=models.DateField(blank=True, null=True, verbose_name='date of birth'),
        ),
    ]
