# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-03 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_auto_20160922_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='context',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='environment',
        ),
        migrations.AlterField(
            model_name='experience',
            name='type',
            field=models.CharField(choices=[(None, 'unknown'), ('PRACT', 'praktykant'), ('ENGEE', 'specjalista/inżynier'), ('MANAG', 'kierownik/manager'), ('FREEL', 'freelancer'), ('OTHER', 'other')], max_length=5, null=True, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/pictures/', verbose_name='image'),
        ),
    ]
