# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-03 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_auto_20161003_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillitem',
            name='category',
            field=models.CharField(choices=[(None, 'unknown'), ('1', 'familiar'), ('2', 'beginner'), ('3', 'skilled'), ('4', 'advanced'), ('5', 'expert')], max_length=5, null=True, verbose_name='category'),
        ),
        migrations.DeleteModel(
            name='SkillType',
        ),
    ]
