# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-08 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0013_auto_20161008_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='responsibility',
        ),
        migrations.AddField(
            model_name='experience',
            name='responsibility_exp',
            field=models.ManyToManyField(to='cv.ResponsibilityItem'),
        ),
    ]
