# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-08 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0014_auto_20161008_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='experience',
            name='responsibility_exp',
            field=models.ManyToManyField(through='cv.Responsibility', to='cv.ResponsibilityItem'),
        ),
        migrations.AddField(
            model_name='responsibility',
            name='experience',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cv.Experience'),
        ),
        migrations.AddField(
            model_name='responsibility',
            name='responsibility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.ResponsibilityItem'),
        ),
    ]
